services:
  time-adjuster:
    build: .
    user: 1004:1004 
    image: truepb/time-adjuster:latest
    container_name: truepb-adjuster
    ports:
      - "8090:80"        # change to 8000 if Flask
    restart: unless-stopped


